In [1]:
import tensorflow as tf

Task 1 – Horizontal Concatenation (Easy)
Create two tensors:

A = [[1,2], [3,4]]

B = [[5,6], [7,8]]

Requirements
Concatenate them using axis=1.
Print:
Original shapes ,
Final shape ,
Resulting tensor

In [ ]:

A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

In [ ]:

C = tf.concat([A, B], axis=1)
C


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

In [20]:

print("A shape:", A.shape)
print("B shape:", B.shape)
print("C shape:", C.shape)

A shape: (2, 2)
B shape: (2, 2)
C shape: (2, 4)


Task 2 – Vertical Concatenation (Easy)
Using the same tensors,

Requirements
Concatenate using axis=0.
Explain why the output shape changed.


In [22]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])


In [23]:
C = tf.concat([A, B], axis=0)
C

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

Task 3 – Shape Prediction (Concept)
Without running the code, predict the output shape.

A = tf.ones((3,4)) B = tf.zeros((3,2))

result = tf.concat([A,B], axis=1)

Questions
What is the output shape?
Why?


In [27]:
A = tf.ones((3,4))
B = tf.zeros((3,2))

In [29]:
result =  tf.concat([A,B] , axis =1)
result  # 3*6 is result matrix x hogi reson rows same h so its be 3 and columns add ho jayegi so itss shhould be 4+2 = 6 

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]], dtype=float32)>

Task 4 – Find the Error (Debugging)
The following code gives an error.

A = tf.ones((2,3)) B = tf.ones((3,3))

result = tf.concat([A,B], axis=1)

Requirements
Explain why the error occurs.
Correct the code in two different ways.


In [32]:
A = tf.ones((2,3)) 
B = tf.ones((3,3))
            
result = tf.concat([A,B], axis=0)  # ROWS not same so fix it when usking the axis =1 and if taking the shame no. of row then  change axis
result

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

Task 5 – Student Marks (Real World)
Create two tensors.

Maths Marks
[[90], [85], [70]]

Science Marks
[[95], [88], [75]]

Requirements
Combine both subjects into one tensor.
Print the final shape.
Expected Output
[[90 95] [85 88] [70 75]]

In [37]:
Maths = [[90], [85], [70]]
Science = [[95], [88], [75]]

result = tf.concat([Maths , Science] , axis =1)
result

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[90, 95],
       [85, 88],
       [70, 75]], dtype=int32)>

Task 6 – RGB Image Simulation (Intermediate)
Create three tensors representing
Red Channel
Green Channel
Blue Channel
Each should have shape

(4,4,1)

Requirements
Combine them into one RGB image.

Expected Shape
(4,4,3)

Hint

Use

tf.concat()

In [38]:
R = tf.ones((4,4,1))
G = tf.zeros((4,4,1))
B = tf.fill((4, 4, 1), 0.5)   # ye sabme 0.5 se bheraga data ko

In [44]:
RGB = tf.concat([R,G,B] , axis =-1)
RGB

<tf.Tensor: shape=(4, 4, 3), dtype=float32, numpy=
array([[[1. , 0. , 0.5],
        [1. , 0. , 0.5],
        [1. , 0. , 0.5],
        [1. , 0. , 0.5]],

       [[1. , 0. , 0.5],
        [1. , 0. , 0.5],
        [1. , 0. , 0.5],
        [1. , 0. , 0.5]],

       [[1. , 0. , 0.5],
        [1. , 0. , 0.5],
        [1. , 0. , 0.5],
        [1. , 0. , 0.5]],

       [[1. , 0. , 0.5],
        [1. , 0. , 0.5],
        [1. , 0. , 0.5],
        [1. , 0. , 0.5]]], dtype=float32)>