In [2]:
# Import TensorFlow library
import tensorflow as tf


In [3]:
# Create a 2D tensor with values 1 to 6
x = tf.constant([[1, 2, 3], [4, 5, 6]])

# Print the tensor
print(x)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [4]:
# Import NumPy for array handling
import numpy as np

# Create a NumPy array
x = np.array([1, 2, 3])

# Convert NumPy array into a TensorFlow tensor
tensor = tf.convert_to_tensor(x)

# Check the data type of the tensor
tensor.dtype


tf.int64

In [5]:
# Convert the tensor to float32 data type
x = tf.cast(x, tf.float32)


In [6]:
# Check the current data type of x
x.dtype


tf.float32

In [7]:
# Generate a random tensor of shape (4, 4)
tf.random.normal((4, 4))


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.84183484,  0.50831705,  0.38658085,  0.8676093 ],
       [ 0.29987532,  0.01132262,  0.36798048,  0.7008546 ],
       [ 0.42070827,  0.7054876 ,  0.22349475,  1.1376727 ],
       [ 0.94320524, -0.40188026,  1.679079  ,  0.7474664 ]],
      dtype=float32)>

In [8]:
# Generate a random tensor with uniform values and a minimum value of 10
tf.random.uniform((3, 3), minval=10)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[7.1113167, 4.986299 , 3.0765405],
       [2.310686 , 7.281311 , 3.5782166],
       [3.3699837, 8.575382 , 9.200456 ]], dtype=float32)>

In [10]:
# Generate a random tensor with uniform values between 10 and 20
tf.random.uniform((3, 3), minval=10, maxval=20)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[12.398029, 18.060665, 17.823982],
       [18.681498, 17.680994, 12.370883],
       [12.96514 , 14.556092, 15.260001]], dtype=float32)>

In [12]:
x = tf.constant([1,2,3])

In [17]:
y = tf.Variable([0.5 , 1 ])

In [19]:
x = tf.cast(x, tf.float16)

In [21]:
x = tf.reshape(x, (3,1))
x

<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[1.],
       [2.],
       [3.]], dtype=float16)>

In [15]:
tf.squeeze(x)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [22]:
tf.expand_dims(x , axis=0)

<tf.Tensor: shape=(1, 3, 1), dtype=float16, numpy=
array([[[1.],
        [2.],
        [3.]]], dtype=float16)>

In [24]:
z = tf.constant([1,2,3,4])
z

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [30]:
z=tf.reshape(z, (2,2))
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [31]:
tf.squeeze(z)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [32]:
a= tf.zeros((3,4))
a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [33]:
one = tf.ones((2,5))
one

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [34]:
s = tf.fill((3,3),  7)
s

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)>