In [ ]:
# Import TensorFlow library
import tensorflow as tf


In [ ]:
# Create a 2D tensor with values 1 to 6
x = tf.constant([[1, 2, 3], [4, 5, 6]])

# Print the tensor
print(x)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# Import NumPy for array handling
import numpy as np

# Create a NumPy array
x = np.array([1, 2, 3])

# Convert NumPy array into a TensorFlow tensor
tensor = tf.convert_to_tensor(x)

# Check the data type of the tensor
tensor.dtype


tf.int64

In [ ]:
# Convert the tensor to float32 data type
x = tf.cast(x, tf.float32)


In [ ]:
# Check the current data type of x
x.dtype


tf.float32

In [16]:
# Generate a random tensor of shape (4, 4)
tf.random.normal((4, 4))


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-1.205941  , -1.2815744 ,  0.72006756, -1.8205848 ],
       [ 0.5372482 , -0.34180623, -0.8155917 ,  1.6345079 ],
       [-1.2896143 ,  0.06624252,  0.44478655,  1.2777966 ],
       [-0.5463505 , -1.6024061 ,  0.41429713, -0.42450836]],
      dtype=float32)>

In [ ]:
# Generate a random tensor with uniform values and a minimum value of 10
tf.random.uniform((3, 3), minval=10)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[3.7760286, 9.470839 , 5.2867527],
       [7.18039  , 7.2306075, 4.615046 ],
       [6.2855697, 7.26858  , 8.274052 ]], dtype=float32)>

In [ ]:
# Generate a random tensor with uniform values between 10 and 20
tf.random.uniform((3, 3), minval=10, maxval=20)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[13.326574, 15.127239, 10.111066],
       [14.728884, 17.127499, 18.169338],
       [11.654798, 15.814215, 19.111555]], dtype=float32)>