In [3]:
# Import TensorFlow library
import tensorflow as tf


In [4]:
# Create a 2D tensor with values 1 to 6
x = tf.constant([[1, 2, 3], [4, 5, 6]])

# Print the tensor
print(x)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
# Import NumPy for array handling
import numpy as np

# Create a NumPy array
x = np.array([1, 2, 3])

# Convert NumPy array into a TensorFlow tensor
tensor = tf.convert_to_tensor(x)

# Check the data type of the tensor
tensor.dtype


tf.int64

In [6]:
# Convert the tensor to float32 data type
x = tf.cast(x, tf.float32)


In [7]:
# Check the current data type of x
x.dtype


tf.float32

In [8]:
# Generate a random tensor of shape (4, 4)
tf.random.normal((4, 4))


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.93189776,  0.9446036 ,  1.4625084 ,  0.7179934 ],
       [-0.35404798,  0.22961655, -1.6066464 ,  1.3147451 ],
       [-0.8695504 ,  0.67842966,  0.23970829, -1.1317403 ],
       [-0.6018962 ,  0.07438973,  0.38266024, -1.375021  ]],
      dtype=float32)>

In [9]:
# Generate a random tensor with uniform values and a minimum value of 10
tf.random.uniform((3, 3), minval=10)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[3.7837229, 7.9275613, 8.723638 ],
       [2.103156 , 3.5811357, 1.3880863],
       [5.385095 , 6.397971 , 1.096426 ]], dtype=float32)>

In [10]:
# Generate a random tensor with uniform values between 10 and 20
tf.random.uniform((3, 3), minval=10, maxval=20)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[11.434846 , 14.583677 , 17.846539 ],
       [12.168606 , 12.222792 , 14.344885 ],
       [13.2574215, 18.61227  , 12.997912 ]], dtype=float32)>

In [ ]:
# Create a 1D tensor with values 1, 2, 3
x = tf.constant([1, 2, 3])
# Display the tensor
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
# Create a TensorFlow variable with two values
y = tf.Variable([0.5, 1])

In [ ]:
# Convert x tensor to float16 data type
x = tf.cast(x, tf.float16)

In [ ]:
# Reshape x from shape (3,) to shape (3, 1)
x = tf.reshape(x, (3, 1))
# Display the reshaped tensor
x

<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[1.],
       [2.],
       [3.]], dtype=float16)>

In [ ]:
# Remove size-one dimensions from x
tf.squeeze(x)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 2., 3.], dtype=float16)>

In [ ]:
# Add a new dimension at axis 0
tf.expand_dims(x, axis=0)

<tf.Tensor: shape=(1, 3, 1), dtype=float16, numpy=
array([[[1.],
        [2.],
        [3.]]], dtype=float16)>

In [ ]:
# Create a 1D tensor with four values
z = tf.constant([1, 2, 3, 4])
# Display the tensor
z

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# Reshape z into a 2x2 matrix
z = tf.reshape(z, (2, 2))
# Display the reshaped tensor
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Remove any size-one dimensions from z
tf.squeeze(z)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Create a 3x4 tensor filled with zeros
a = tf.zeros((3, 4))
# Display the zero tensor
a

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Create a 2x5 tensor filled with ones
one = tf.ones((2, 5))
# Display the ones tensor
one

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a 3x3 tensor filled with the value 7
s = tf.fill((3, 3), 7)
# Display the filled tensor
s

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)>

In [ ]:
# Create a tensor with values 0 through 9
new = tf.range(10)
# Display the range tensor
new

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Create a tensor with values 10,20,...,100
old = tf.range(10, 110, 10)
# Display the range tensor
old

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100], dtype=int32)>

In [ ]:
# Join the new and old tensors along axis 0
tf.concat([new, old], axis=0)

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  20,  30,
        40,  50,  60,  70,  80,  90, 100], dtype=int32)>

In [ ]:
# Compute the mean of new
tf.reduce_mean(new)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
# Compute the sum of new
tf.reduce_sum(new)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [ ]:
# Shuffle the elements of old randomly
tf.random.shuffle(old)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 50,  30,  20,  90, 100,  40,  60,  80,  70,  10], dtype=int32)>