In [ ]:
import torch  # import the PyTorch library for tensor operations

In [ ]:
x = torch.randint(0, 20, (2, 3, 4))  # create a random integer tensor with shape [2,3,4]

In [ ]:
x  # display the tensor values

tensor([[[ 7, 18, 11, 15],
         [11,  1, 10,  3],
         [ 2, 14, 17,  3]],

        [[12,  4,  9, 14],
         [17,  5,  8,  5],
         [13, 17,  8, 18]]])

In [ ]:
x.shape  # show tensor shape: 2 blocks, 3 rows, 4 columns

torch.Size([2, 3, 4])

In [ ]:
x.dtype  # display the element data type of the tensor

torch.int64

In [ ]:
x.reshape(6, 4)  # reshape the tensor into shape [6,4]

tensor([[ 7, 18, 11, 15],
        [11,  1, 10,  3],
        [ 2, 14, 17,  3],
        [12,  4,  9, 14],
        [17,  5,  8,  5],
        [13, 17,  8, 18]])

In [ ]:
x.unsqueeze(0).shape  # add a new leading dimension and show the new shape

torch.Size([1, 2, 3, 4])

In [ ]:
y = x.flatten()  # flatten the tensor into a 1D vector

In [ ]:
y.shape  # show the shape of the flattened tensor

torch.Size([24])

In [ ]:
z = torch.randint(0, 20, (2, 3, 4))  # create another random tensor with same shape

In [ ]:
z  # display the second tensor values

tensor([[[11, 18,  2, 16],
         [12,  8, 11,  9],
         [12, 13, 19,  1]],

        [[ 6, 15,  7,  7],
         [ 0,  3,  8,  2],
         [13,  6, 10,  3]]])

In [ ]:
conct = torch.concat([x, z])  # concatenate x and z along the first dimension
conct  # display the concatenated tensor

tensor([[[ 7, 18, 11, 15],
         [11,  1, 10,  3],
         [ 2, 14, 17,  3]],

        [[12,  4,  9, 14],
         [17,  5,  8,  5],
         [13, 17,  8, 18]],

        [[11, 18,  2, 16],
         [12,  8, 11,  9],
         [12, 13, 19,  1]],

        [[ 6, 15,  7,  7],
         [ 0,  3,  8,  2],
         [13,  6, 10,  3]]])

In [ ]:
stack_meth = torch.stack([x, z])  # stack x and z into a new dimension
stack_meth  # display the stacked tensor

tensor([[[[ 7, 18, 11, 15],
          [11,  1, 10,  3],
          [ 2, 14, 17,  3]],

         [[12,  4,  9, 14],
          [17,  5,  8,  5],
          [13, 17,  8, 18]]],


        [[[11, 18,  2, 16],
          [12,  8, 11,  9],
          [12, 13, 19,  1]],

         [[ 6, 15,  7,  7],
          [ 0,  3,  8,  2],
          [13,  6, 10,  3]]]])

In [ ]:
x.max()  # compute the maximum value in tensor x

tensor(18)

In [ ]:
x.argmax()  # compute the index of the maximum value in the flattened tensor

tensor(1)

In [ ]:
conct.sum()  # compute the sum of all elements in the concatenated tensor

tensor(454)

In [ ]:
torch.sum(x)  # compute the sum of all elements in tensor x using torch.sum

tensor(242)

In [ ]:
torch.relu(x)  # apply rectified linear unit activation to x

tensor([[[ 7, 18, 11, 15],
         [11,  1, 10,  3],
         [ 2, 14, 17,  3]],

        [[12,  4,  9, 14],
         [17,  5,  8,  5],
         [13, 17,  8, 18]]])