In [ ]:
import torch as pt

# Print the installed PyTorch version
print(pt.__version__)

2.11.0+cpu


In [ ]:
# Create a 3D tensor and inspect its number of dimensions
x = pt.tensor([[[1,2],[3,4]]])  # 3D matrix
x.ndim

3

In [ ]:
# Compute the matrix product of two 2x2 tensors
a = pt.tensor([[1, 3], [2, 4]])
b = pt.tensor([[5, 7], [6, 8]])

print(pt.matmul(a, b))    # matmul is used for matrix multiplication

tensor([[23, 31],
        [34, 46]])


In [ ]:
# Another way to compute matrix multiplication using the @ operator
a @ b

tensor([[23, 31],
        [34, 46]])

In [ ]:
# Compute the dot product of two 1D tensors
a = pt.tensor([1, 3, 2])
b = pt.tensor([5, 7, 6])

result = pt.dot(a, b)
print(result)

tensor(38)


In [ ]:
import numpy as np
arr = np.array([1,2,3])
# Convert a NumPy array to a PyTorch tensor
tensor = pt.from_numpy(arr)
print(tensor)


tensor([1, 2, 3])


In [ ]:
# Check whether CUDA is available on this machine
pt.cuda.is_available()

False

In [ ]:
# Choose device based on GPU availability and move a tensor to it
device = "cuda" if pt.cuda.is_available() else "cpu"
x = pt.tensor([1,2,3]).to(device)
print(x)

tensor([1, 2, 3])


Neural Networks


In [ ]:
import torch.nn as nn
# Build a simple feedforward neural network model
model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)

print(model)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)


In [ ]:
# Create sample input and output tensors for training or testing
x  = pt.tensor([[1] , [2],[3], [4],[5]] , dtype = pt.float32)
y  = pt.tensor([[2] , [4],[6], [8],[10]] , dtype = pt.float32)

In [74]:
# Task1
# . 0D tensor
# . 1D tensor
# . 2D tensor
# . 3D tensor

# print
# 1.shape
# 2. ndim
# 3. dtype

In [ ]:
# Create a 2D tensor and inspect its properties
x  = pt.tensor([[1] , [2],[3], [4],[5]] , dtype = pt.float32)
print(x)
x.ndim

x.shapex.dtype

torch.float32

In [ ]:
# Create a 3D tensor and inspect its properties
x  = pt.tensor([[[1] , [2],[3], [4],[5]]] , dtype = pt.float32)
print(x)
x.ndim

x.shapex.dtype

torch.float32

In [ ]:
# Create a scalar tensor and inspect its properties
z = pt.tensor(5)
print(z)
z.ndim
z.shape
z.dtype

tensor(5)


torch.int64

In [ ]:
# Create a 1D tensor and inspect its properties
s = pt.tensor([1,2,3])
s.ndim
s.shape
s.dtype

torch.int64

Tasks 

# create two random tensors of shape (3,3) and perform
- Adition 
- Subtraction 
- Element wise multiplication 
- Matrix Multipllication

In [ ]:
# Create the first 3x3 tensor and inspect its shape
x =  pt.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x.shape)

torch.Size([3, 3])

In [ ]:
# Create the second 3x3 tensor and inspect its shape
y  = pt.tensor([[10,11,12], [13,14,15] , [16,17,18]])
print(y.shape)

torch.Size([3, 3])

In [ ]:
# Add the two tensors elementwise
result = pt.add(x,y)   # result = x + y
result

tensor([[11, 13, 15],
        [17, 19, 21],
        [23, 25, 27]])

In [ ]:
# Subtract the second tensor from the first
result2 = pt.sub(x,y)
result2

tensor([[-9, -9, -9],
        [-9, -9, -9],
        [-9, -9, -9]])

In [ ]:
# Multiply the tensors elementwise
result3 = pt.mul(x,y)
result3

tensor([[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]])

In [ ]:
# Compute the matrix multiplication of x and y
result4 = x@y
result4

tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

# Task

create a tensor from 1 to 14 then
- Reshape it into (4,6)
- Reshape it into (2,3,4)
- print the  shape afte each operation


In [85]:
# Create a 1D tensor with values from 1 to 24
tensor = pt.arange(1, 25)
print(tensor)
# Show the original tensor shape
tensor.shape

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])


torch.Size([24])

In [86]:
# Reshape the tensor into a 4x6 matrix
tensor1 = pt.reshape(tensor ,(4,6))
# Show the shape of the reshaped tensor
tensor1.shape

torch.Size([4, 6])

In [87]:
# Reshape the original tensor into a 3D tensor with shape (2,3,4)
tensor2 = pt.reshape(tensor ,(2,3,4))
# Show the shape of the 3D tensor
tensor2.shape

torch.Size([2, 3, 4])

In [88]:
# Create a tensor and print the index of the maximum value
x = pt.tensor([3,5,1,4])
print(pt.argmax(x))

tensor(1)


In [ ]:
# Create a tensor and print the index of the minimum value
x = pt.tensor([3,5,1,4])
print(pt.argmin(x))

tensor(2)


In [ ]:
# Create a score tensor and compute softmax probabilities along the first dimension
scores = pt.tensor([[2.  , 5. , 6. , 4. , 3. , 8., 3.3]])
pt.softmax(scores , dim =0)

tensor([[1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# Apply the ReLU activation function elementwise
pt.relu(pt.tensor([-4., 3., -2., 7.]))

tensor([0., 3., 0., 7.])

In [113]:
# Clamp tensor values so they all lie between 2 and 20
M = pt.tensor([-5, 2, 8, 15, 30])
pt.clamp(M , min = 2 , max = 20)

tensor([ 2,  2,  8, 15, 20])

In [111]:
import torch as pt

a = pt.rand(20)
b = pt.rand(20)

result = pt.einsum("i,i->", a, b)

print(result)

tensor(4.0154)


In [114]:
A = pt.tensor([[1,2,3],
               [4,5,6]])

In [116]:
A.sum()

tensor(21)

In [117]:
pt.einsum("ij ->", A)

tensor(21)

In [119]:
pt.einsum("ij->j" , A)

tensor([5, 7, 9])

In [ ]:
pt.e