In [2]:
import torch as pt

print(pt.__version__)

2.11.0+cpu


In [3]:
x = pt.tensor([[[1,2],[3,4]]])  #3d matrix
x.ndim

3

In [4]:
# cross product
a = pt.tensor([[1, 3], [2, 4]])
b = pt.tensor([[5, 7], [6, 8]])

print(pt.matmul(a, b))    # matmul is use for  cross product

tensor([[23, 31],
        [34, 46]])


In [5]:
a @ b #second method for cross product

tensor([[23, 31],
        [34, 46]])

In [6]:
a = pt.tensor([1, 3, 2])
b = pt.tensor([5, 7, 6])

result = pt.dot(a, b)
print(result)

tensor(38)


In [7]:
import numpy as np
arr = np.array([1,2,3])
tensor = pt.from_numpy(arr)   # array ko  tensor mai covert  krna
print(tensor)


tensor([1, 2, 3])


In [8]:
pt.cuda.is_available()  #GPU h ya nhi pc mai

False

In [9]:
device = "cuda" if pt.cuda.is_available() else "cpu"
x = pt.tensor([1,2,3]).to(device)
print(x)

tensor([1, 2, 3])


Neural Networks


In [10]:
import torch.nn as nn
model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)

print(model)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)


In [11]:
x  = pt.tensor([[1] , [2],[3], [4],[5]] , dtype = pt.float32)
y  = pt.tensor([[2] , [4],[6], [8],[10]] , dtype = pt.float32)

In [12]:
# Task1
# . 0D tensor
# . 1D tensor
# . 2D tensor
# . 3D tensor

# print
# 1.shape
# 2. ndim
# 3. dtype

In [13]:
x  = pt.tensor([[1] , [2],[3], [4],[5]] , dtype = pt.float32)
x.ndim
x.shape
x.dtype

torch.float32

In [14]:
x  = pt.tensor([[[1] , [2],[3], [4],[5]]] , dtype = pt.float32)
x.ndim
x.shape
x.dtype

torch.float32

In [15]:
z = pt.tensor(5)
print(z)
z.ndim
z.shape
z.dtype

tensor(5)


torch.int64

In [16]:
s = pt.tensor([1,2,3])
s.ndim
s.shape
s.dtype

torch.int64

Tasks 

# create two random tensors of shape (3,3) and perform
- Adition 
- Subtraction 
- Element wise multiplication 
- Matrix Multipllication

In [20]:
x =  pt.tensor([[1,2,3], [4,5,6], [7,8,9]])
x.shape

torch.Size([3, 3])

In [23]:
y  = pt.tensor([[10,11,12], [13,14,15] , [16,17,18]])
y.shape

torch.Size([3, 3])

In [ ]:
result = pt.add(x,y)   # result = x+y
result

tensor([[11, 13, 15],
        [17, 19, 21],
        [23, 25, 27]])

In [ ]:
result2 = pt.sub(x,y)
result2

tensor([[-9, -9, -9],
        [-9, -9, -9],
        [-9, -9, -9]])

In [31]:
result3 = pt.mul(x,y)
result3

tensor([[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]])

In [32]:
result4 = x@y
result4

tensor([[ 84,  90,  96],
        [201, 216, 231],
        [318, 342, 366]])

# Task

create a tensor from 1 to 14 then
- Reshape it into (4,6)
- Reshape it into (2,3,4)
- print the  shape afte each operation


In [47]:
tensor = pt.arange(1, 25)
print(tensor)
tensor.shape

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])


torch.Size([24])

In [50]:
tensor1 = pt.reshape(tensor ,(4,6))
tensor1.shape

torch.Size([4, 6])

In [51]:
tensor2 = pt.reshape(tensor ,(2,3,4))
tensor2.shape

torch.Size([2, 3, 4])