In [19]:
import torch as pt

print(pt.__version__)

2.11.0+cpu


In [ ]:
x = pt.tensor([[[1,2],[3,4]]])  #3d matrix
x.ndim

3

In [ ]:
# cross product
a = pt.tensor([[1, 3], [2, 4]])
b = pt.tensor([[5, 7], [6, 8]])

print(pt.matmul(a, b))    # matmul is use for  cross product

tensor([[23, 31],
        [34, 46]])


In [ ]:
a @ b #second method for cross product

tensor([[23, 31],
        [34, 46]])

In [35]:
a = pt.tensor([1, 3, 2])
b = pt.tensor([5, 7, 6])

result = pt.dot(a, b)
print(result)

tensor(38)


In [33]:
import numpy as np
arr = np.array([1,2,3])
tensor = pt.from_numpy(arr)   # array ko  tensor mai covert  krna
print(tensor)


tensor([1, 2, 3])


In [ ]:
pt.cuda.is_available()  #GPU h ya nhi pc mai

False